# with_items we list packages we can install in sequence now. ex: yum httpd, yum binutills, yum nodejs
-
    name: 'Install required packages'
    hosts: localhost
    vars:
        packages:
            - httpd
            - binutils
            - glibc
            - ksh
            - libaio
            - libXext
            - gcc
            - make
            - sysstat
            - unixODBC
            - mongodb
            - nodejs
            - grunt
    tasks:
        -
            yum: 
              name: '{{ items }}'
              state: present
            with_items: '{{packages}}'